services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: hhttps://github.com/Nananina2004/zyldyzAI-backend.git
    region: frankfurt
    branch: main
    envVars:
      - key: MONGO_URL
        sync: false
    buildFilter:
      paths:
      - app/**
  
